RUBBERBAND_VERSION = 3.3.0
RUBBERBAND_SOURCE = rubberband-$(RUBBERBAND_VERSION).tar.gz
RUBBERBAND_SITE = $(call github,breakfastquay,rubberband,v$(RUBBERBAND_VERSION))
RUBBERBAND_INSTALL_STAGING = YES
RUBBERBAND_INSTALL_TARGET = YES
RUBBERBAND_LICENSE = GPLv2

ifeq ($(BR2_PACKAGE_FFTW_DOUBLE),y)
RUBBERBAND_DEPENDENCIES += fftw-double
endif

ifeq ($(BR2_PACKAGE_KISSFFT),y)
RUBBERBAND_DEPENDENCIES += kissfft
endif

ifeq ($(BR2_PACKAGE_LADSPA),y)
RUBBERBAND_DEPENDENCIES += ladspa
endif

ifeq ($(BR2_PACKAGE_LIBSAMPLERATE),y)
RUBBERBAND_DEPENDENCIES += libsamplerate
endif

ifeq ($(BR2_PACKAGE_LIBSNDFILE),y)
RUBBERBAND_DEPENDENCIES += libsndfile
endif

ifeq ($(BR2_PACKAGE_LV2),y)
RUBBERBAND_DEPENDENCIES += lv2
endif

ifeq ($(BR2_PACKAGE_SPEEX),y)
RUBBERBAND_DEPENDENCIES += speex
endif

ifeq ($(BR2_PACKAGE_VAMP_SDK),y)
RUBBERBAND_DEPENDENCIES += vamp-sdk
endif

ifeq ($(BR2_PACKAGE_RUBBERBAND_FFT_FFTW),y)
RUBBERBAND_DEPENDENCIES += fftw-double
RUBBERBAND_CONF_OPTS += -Dfft=fftw
else
ifeq ($(BR2_PACKAGE_RUBBERBAND_FFT_KISSFFT),y)
RUBBERBAND_DEPENDENCIES += kissfft
RUBBERBAND_CONF_OPTS += -Dfft=kissfft
else
RUBBERBAND_CONF_OPTS += -Dfft=builtin
endif
endif

ifeq ($(BR2_PACKAGE_RUBBERBAND_RESAMPLER_LIBSAMPLERATE),y)
RUBBERBAND_DEPENDENCIES += libsamplerate
RUBBERBAND_CONF_OPTS += -Dresampler=libsamplerate
else
RUBBERBAND_CONF_OPTS += -Dresampler=builtin
endif

ifeq ($(BR2_PACKAGE_BOOST_TEST),y)
RUBBERBAND_CONF_OPTS += -Dtests=enabled
RUBBERBAND_DEPENDENCIES += boost
else
RUBBERBAND_CONF_OPTS += -Dtests=disabled
endif

$(eval $(meson-package))
